a=('bhuvan','santoshi','rakshita','rakshit','tanush','tanush')
print(min(a))
print(max(a))
b=(10,2,False<True,23)
print(min(b))
print(max(b))
print(b)
name=input("enter a names & separated with comma : ")
print(name.split(","))
print(tuple(name.split(",")))
names=(tuple(name.split(",")),a)
print(names)
print(names[:2])
print(len(names[1]))
print((names[1][1]))
del names
print(names)